"""Persisted entities.

Two shapes here are load-bearing and worth explaining before the code:

**Systems and worlds are persisted only once someone reaches them.** Space is
infinite and generated by a pure function of ``(universe_seed, sector, index)``,
so an unvisited system needs no row -- it can be recomputed identically by
anyone, any time. A row appears at first visit, because that is the moment the
system acquires state that generation cannot derive: who owns what, what has
been mined out, who has a colony there. See :mod:`galaxysim.worldgen`.

**Resources are a JSON bag, not columns.** ``new_resource_type`` is a legal tech
effect, so the set of resources a civilization deals in is open-ended and
different per civ. A fixed column per resource cannot express that.
"""

from __future__ import annotations

import enum
from datetime import datetime, timezone

from sqlalchemy import (
    BigInteger,
    Boolean,
    DateTime,
    Float,
    ForeignKey,
    Index,
    Integer,
    JSON,
    String,
    Text,
    UniqueConstraint,
)
from sqlalchemy.ext.mutable import MutableDict
from sqlalchemy.orm import Mapped, mapped_column, relationship

from galaxysim.core.space import Vec3
from galaxysim.model.base import Base

# JSON dicts must be wrapped in MutableDict or in-place edits (the normal way to
# update a resource bag) never mark the row dirty and are silently lost on
# commit.
JSONDict = MutableDict.as_mutable(JSON)


def _utcnow() -> datetime:
    return datetime.now(timezone.utc)


class UniverseMode(str, enum.Enum):
    SOLO = "solo"
    MULTIPLAYER = "multiplayer"


class IntentKind(str, enum.Enum):
    """What a player can queue between ticks."""

    MOVE_FLEET = "move_fleet"
    COLONIZE = "colonize"
    BUILD_FLEET = "build_fleet"
    BUILD_STRUCTURE = "build_structure"
    TRANSFER_CARGO = "transfer_cargo"
    SUPPLY_ROUTE = "supply_route"
    ATTACK = "attack"
    RESEARCH = "research"


class IntentStatus(str, enum.Enum):
    QUEUED = "queued"
    IN_PROGRESS = "in_progress"
    COMPLETED = "completed"
    FAILED = "failed"
    CANCELLED = "cancelled"


class Universe(Base):
    """One shared world with its own clock and seed."""

    __tablename__ = "universes"

    id: Mapped[int] = mapped_column(primary_key=True)
    name: Mapped[str] = mapped_column(String(120))
    seed: Mapped[int] = mapped_column(BigInteger)
    tick_number: Mapped[int] = mapped_column(Integer, default=0)
    #: Cadence is stored per universe so a solo game and the shared universe can
    #: run at different resolutions without touching balance -- see
    #: :mod:`galaxysim.engine.rates`.
    seconds_per_tick: Mapped[int] = mapped_column(Integer, default=300)
    mode: Mapped[str] = mapped_column(String(20), default=UniverseMode.SOLO.value)
    created_at: Mapped[datetime] = mapped_column(DateTime(timezone=True), default=_utcnow)

    civs: Mapped[list["Civ"]] = relationship(
        back_populates="universe", cascade="all, delete-orphan"
    )
    systems: Mapped[list["StarSystem"]] = relationship(
        back_populates="universe", cascade="all, delete-orphan"
    )

    def __repr__(self) -> str:
        return f"<Universe {self.name!r} tick={self.tick_number}>"


class Civ(Base):
    """A player's or AI's civilization."""

    __tablename__ = "civs"

    id: Mapped[int] = mapped_column(primary_key=True)
    universe_id: Mapped[int] = mapped_column(
        ForeignKey("universes.id", ondelete="CASCADE"), index=True
    )
    name: Mapped[str] = mapped_column(String(120))
    species_name: Mapped[str] = mapped_column(String(120), default="")
    #: The player's free-text species description. Kept verbatim so a civ can be
    #: regenerated from it, and so the extraction step can be re-run if the
    #: schema changes. See :mod:`galaxysim.species`.
    species_description: Mapped[str] = mapped_column(Text, default="")
    is_ai: Mapped[bool] = mapped_column(Boolean, default=False)
    #: Per-civ seed, derived once from the universe seed and the civ's identity.
    #: Every roll specific to this civ descends from it.
    seed: Mapped[int] = mapped_column(BigInteger, default=0)

    #: Research **already paid for in materials** and not yet spent on a tech.
    #:
    #: Knowledge is the one thing that is civ-wide: a discovery is known
    #: everywhere the moment it is made. Matter is not -- there is no civ
    #: treasury, only the stockpile each colony holds (:attr:`Colony.stockpile`),
    #: and every point in this pool was bought out of one of them. There are no
    #: free abstract research points: a colony with laboratories, workers and an
    #: empty warehouse produces nothing.
    research_progress: Mapped[float] = mapped_column(Float, default=0.0)
    #: Cumulative research ever paid. The balance invariant ties total power to
    #: this number, so it is never spent down -- ``research_progress`` is the
    #: spendable pool, this is the odometer.
    research_invested: Mapped[float] = mapped_column(Float, default=0.0)
    #: Placeholder for the generated tech lineage of build-order step 5. Until
    #: genomes exist, "how far along" a civ is collapses to a single depth
    #: counter, which is enough to exercise the superlinear cost curve and the
    #: research half of the tick loop.
    techs_known: Mapped[int] = mapped_column(Integer, default=0)

    universe: Mapped[Universe] = relationship(back_populates="civs")
    colonies: Mapped[list["Colony"]] = relationship(
        back_populates="civ", cascade="all, delete-orphan"
    )
    fleets: Mapped[list["Fleet"]] = relationship(
        back_populates="civ", cascade="all, delete-orphan"
    )

    __table_args__ = (UniqueConstraint("universe_id", "name", name="uq_civ_name_per_universe"),)

    def __repr__(self) -> str:
        return f"<Civ {self.name!r}{' (AI)' if self.is_ai else ''}>"


class StarSystem(Base):
    """A gravitational cluster of worlds, materialized on first visit.

    Position is absolute in light-years. The sector/index pair is the generation
    key that produced it, retained so the row can be checked against a fresh
    generation run.
    """

    __tablename__ = "star_systems"

    id: Mapped[int] = mapped_column(primary_key=True)
    universe_id: Mapped[int] = mapped_column(
        ForeignKey("universes.id", ondelete="CASCADE"), index=True
    )
    sector_i: Mapped[int] = mapped_column(Integer)
    sector_j: Mapped[int] = mapped_column(Integer)
    sector_k: Mapped[int] = mapped_column(Integer)
    #: Which system within the sector, in generation order.
    index_in_sector: Mapped[int] = mapped_column(Integer)

    name: Mapped[str] = mapped_column(String(120))
    x: Mapped[float] = mapped_column(Float)
    y: Mapped[float] = mapped_column(Float)
    z: Mapped[float] = mapped_column(Float)
    star_class: Mapped[str] = mapped_column(String(40), default="")
    #: Tick at which this system was first visited and therefore persisted.
    discovered_tick: Mapped[int] = mapped_column(Integer, default=0)

    universe: Mapped[Universe] = relationship(back_populates="systems")
    worlds: Mapped[list["World"]] = relationship(
        back_populates="system", cascade="all, delete-orphan"
    )

    __table_args__ = (
        UniqueConstraint(
            "universe_id",
            "sector_i",
            "sector_j",
            "sector_k",
            "index_in_sector",
            name="uq_system_generation_key",
        ),
        Index("ix_system_sector", "universe_id", "sector_i", "sector_j", "sector_k"),
    )

    @property
    def position(self) -> Vec3:
        return Vec3(self.x, self.y, self.z)

    def __repr__(self) -> str:
        return f"<StarSystem {self.name!r} at ({self.x:.2f}, {self.y:.2f}, {self.z:.2f})>"


class World(Base):
    """A colonizable (or not) body within a system."""

    __tablename__ = "worlds"

    id: Mapped[int] = mapped_column(primary_key=True)
    system_id: Mapped[int] = mapped_column(
        ForeignKey("star_systems.id", ondelete="CASCADE"), index=True
    )
    name: Mapped[str] = mapped_column(String(120))
    world_type: Mapped[str] = mapped_column(String(40))
    orbit_index: Mapped[int] = mapped_column(Integer, default=0)

    #: 0.0-1.0, and **derived** rather than rolled: a conclusion drawn from
    #: atmosphere, temperature, gravity, radiation shielding, water and
    #: biosphere. See :func:`galaxysim.worldgen.survey.derive_habitability`.
    habitability: Mapped[float] = mapped_column(Float, default=0.0)
    #: The world's full physical description -- star, orbit, body, atmosphere,
    #: climate, hydrosphere, biosphere, geology, moons. Stored as one document
    #: because almost all of it is read-only after generation and displayed
    #: rather than queried. Terraforming writes back through it.
    #: See :mod:`galaxysim.worldgen.serialize`.
    survey: Mapped[dict] = mapped_column(JSONDict, default=dict)
    #: Usable surface in square kilometres, from radius and land fraction.
    #: Real area, so a superearth genuinely holds more than a moon.
    land_area_km2: Mapped[float] = mapped_column(Float, default=0.0)
    #: How many people this world could ultimately support, from real land area
    #: at a real population density scaled by how pleasant it is.
    carrying_capacity: Mapped[float] = mapped_column(Float, default=0.0)
    #: 0.0-1.0 environmental danger, applied against colony growth.
    hazard: Mapped[float] = mapped_column(Float, default=0.0)
    #: How many structures this world can host. Part of its identity, not a
    #: global constant: a cramped gas giant supports far less than a
    #: terrestrial, so what a world is *for* is decided partly here.
    slots: Mapped[int] = mapped_column(Integer, default=4)
    description: Mapped[str] = mapped_column(Text, default="")

    system: Mapped[StarSystem] = relationship(back_populates="worlds")
    colony: Mapped["Colony | None"] = relationship(
        back_populates="world", cascade="all, delete-orphan", uselist=False
    )

    def __repr__(self) -> str:
        return f"<World {self.name!r} ({self.world_type})>"


class Colony(Base):
    """A civilization's settlement on a world. At most one per world.

    A colony is a *place*, not a line in a civ-wide ledger. It holds its own
    stockpile, and there is no treasury behind it: ore mined here is here
    until a ship carries it somewhere else. That is what makes a remote outpost
    genuinely remote, and what gives supply lines something to cut.
    """

    __tablename__ = "colonies"

    id: Mapped[int] = mapped_column(primary_key=True)
    #: Unique: a world holds at most one colony, so capturing one means
    #: reassigning this row rather than inserting a second.
    world_id: Mapped[int] = mapped_column(
        ForeignKey("worlds.id", ondelete="CASCADE"), unique=True, index=True
    )
    civ_id: Mapped[int] = mapped_column(ForeignKey("civs.id", ondelete="CASCADE"), index=True)

    name: Mapped[str] = mapped_column(String(120))
    population: Mapped[float] = mapped_column(Float, default=1.0)
    infrastructure: Mapped[float] = mapped_column(Float, default=1.0)
    founded_tick: Mapped[int] = mapped_column(Integer, default=0)

    #: Resources physically present here. Everything this colony pays for comes
    #: out of this bag, and nothing else can spend it without shipping it first.
    stockpile: Mapped[dict] = mapped_column(JSONDict, default=dict)

    #: Fractions of the population assigned to each labor sector, normalized to
    #: sum to 1. See :mod:`galaxysim.colony.labor`.
    labor: Mapped[dict] = mapped_column(JSONDict, default=dict)

    #: Recipe key -> relative weight: which refining chains this colony's
    #: industry runs, and in what proportion. Empty means "work through
    #: everything you can", which keeps an unattended colony alive and is
    #: deliberately worse than a plan somebody chose.
    #: See :mod:`galaxysim.materials.refining`.
    refining: Mapped[dict] = mapped_column(JSONDict, default=dict)

    #: ``manual`` or ``governor``. Colony depth is opt-in: a governed colony
    #: runs itself to a policy, so a large empire does not require managing
    #: every world by hand. New colonies default to governed.
    management_mode: Mapped[str] = mapped_column(String(20), default="governor")
    #: Which policy a governed colony follows. See
    #: :mod:`galaxysim.engine.resolvers.governor`.
    governor_policy: Mapped[str] = mapped_column(String(20), default="balanced")

    @property
    def is_governed(self) -> bool:
        return self.management_mode == "governor"

    world: Mapped[World] = relationship(back_populates="colony")
    civ: Mapped[Civ] = relationship(back_populates="colonies")
    buildings: Mapped[list["Building"]] = relationship(
        back_populates="colony", cascade="all, delete-orphan"
    )

    def __repr__(self) -> str:
        return f"<Colony {self.name!r} pop={self.population:.1f}>"


class Building(Base):
    """A structure on a colony, under construction or finished.

    Construction is progress-based rather than timed: a building consumes
    industry-work each tick from whatever its colony's industry sector produces.
    A colony with nobody assigned to industry never finishes anything, which is
    what makes the labor allocation a real decision rather than a display.
    """

    __tablename__ = "buildings"

    id: Mapped[int] = mapped_column(primary_key=True)
    colony_id: Mapped[int] = mapped_column(
        ForeignKey("colonies.id", ondelete="CASCADE"), index=True
    )
    #: Matches a kind in :data:`galaxysim.colony.buildings.BUILDING_TYPES`.
    kind: Mapped[str] = mapped_column(String(40))
    #: Industry-work still needed. Zero means finished and contributing.
    work_remaining: Mapped[float] = mapped_column(Float, default=0.0)
    started_tick: Mapped[int] = mapped_column(Integer, default=0)
    completed_tick: Mapped[int | None] = mapped_column(Integer, nullable=True)

    colony: Mapped[Colony] = relationship(back_populates="buildings")

    @property
    def is_complete(self) -> bool:
        return self.work_remaining <= 0.0

    def __repr__(self) -> str:
        state = "complete" if self.is_complete else f"{self.work_remaining:.1f} work left"
        return f"<Building {self.kind} ({state})>"


class Fleet(Base):
    """Ships in continuous space.

    A fleet in transit stores its origin, destination and the tick it arrives.
    Position is recomputed by interpolation each tick rather than integrated
    step by step, so a fleet's path does not drift if the cadence changes
    mid-flight.
    """

    __tablename__ = "fleets"

    id: Mapped[int] = mapped_column(primary_key=True)
    universe_id: Mapped[int] = mapped_column(
        ForeignKey("universes.id", ondelete="CASCADE"), index=True
    )
    civ_id: Mapped[int] = mapped_column(ForeignKey("civs.id", ondelete="CASCADE"), index=True)
    name: Mapped[str] = mapped_column(String(120))

    strength: Mapped[float] = mapped_column(Float, default=1.0)
    #: Colony ships carried; consumed one per successful colonization.
    colony_pods: Mapped[int] = mapped_column(Integer, default=0)
    speed_ly_per_hour: Mapped[float] = mapped_column(Float, default=1.0)

    #: Goods currently aboard. A freighter is just a fleet with capacity, which
    #: is why moving cargo reuses the ordinary movement resolver rather than
    #: needing a second one.
    cargo: Mapped[dict] = mapped_column(JSONDict, default=dict)
    cargo_capacity: Mapped[float] = mapped_column(Float, default=0.0)

    x: Mapped[float] = mapped_column(Float)
    y: Mapped[float] = mapped_column(Float)
    z: Mapped[float] = mapped_column(Float)

    origin_x: Mapped[float | None] = mapped_column(Float, nullable=True)
    origin_y: Mapped[float | None] = mapped_column(Float, nullable=True)
    origin_z: Mapped[float | None] = mapped_column(Float, nullable=True)
    dest_x: Mapped[float | None] = mapped_column(Float, nullable=True)
    dest_y: Mapped[float | None] = mapped_column(Float, nullable=True)
    dest_z: Mapped[float | None] = mapped_column(Float, nullable=True)
    departed_tick: Mapped[int | None] = mapped_column(Integer, nullable=True)
    arrival_tick: Mapped[int | None] = mapped_column(Integer, nullable=True)

    civ: Mapped[Civ] = relationship(back_populates="fleets")

    @property
    def position(self) -> Vec3:
        return Vec3(self.x, self.y, self.z)

    @property
    def in_transit(self) -> bool:
        return self.arrival_tick is not None

    @property
    def cargo_tonnage(self) -> float:
        return sum(self.cargo.values())

    @property
    def cargo_space(self) -> float:
        return max(0.0, self.cargo_capacity - self.cargo_tonnage)

    def __repr__(self) -> str:
        return f"<Fleet {self.name!r} str={self.strength:.1f}>"


class Intent(Base):
    """A queued order, resolved on the next tick.

    Orders are never applied at submission time. Everyone's queue resolves
    together on the tick, which is what makes async play fair: being awake when
    you submit confers no advantage.
    """

    __tablename__ = "intents"

    id: Mapped[int] = mapped_column(primary_key=True)
    universe_id: Mapped[int] = mapped_column(
        ForeignKey("universes.id", ondelete="CASCADE"), index=True
    )
    civ_id: Mapped[int] = mapped_column(ForeignKey("civs.id", ondelete="CASCADE"), index=True)

    kind: Mapped[str] = mapped_column(String(30))
    payload: Mapped[dict] = mapped_column(JSONDict, default=dict)
    status: Mapped[str] = mapped_column(String(20), default=IntentStatus.QUEUED.value, index=True)

    queued_tick: Mapped[int] = mapped_column(Integer, default=0)
    resolved_tick: Mapped[int | None] = mapped_column(Integer, nullable=True)
    #: Why a failed intent failed, shown back to the player in their event log.
    result: Mapped[str] = mapped_column(Text, default="")

    def __repr__(self) -> str:
        return f"<Intent {self.kind} {self.status}>"


class Event(Base):
    """One line of a civilization's "what happened while you were away" log.

    ``civ_id`` is null for universe-wide events.
    """

    __tablename__ = "events"

    id: Mapped[int] = mapped_column(primary_key=True)
    universe_id: Mapped[int] = mapped_column(
        ForeignKey("universes.id", ondelete="CASCADE"), index=True
    )
    civ_id: Mapped[int | None] = mapped_column(
        ForeignKey("civs.id", ondelete="CASCADE"), nullable=True, index=True
    )
    tick: Mapped[int] = mapped_column(Integer, index=True)
    kind: Mapped[str] = mapped_column(String(40))
    message: Mapped[str] = mapped_column(Text)
    payload: Mapped[dict] = mapped_column(JSONDict, default=dict)

    def __repr__(self) -> str:
        return f"<Event t={self.tick} {self.kind}: {self.message}>"
